server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:/db.changelog/app-changelog.xml
    default-schema: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true
    username: root
    password:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

